-- ═══════════ 화면 그림(page_drawings) — DB 최종 상태 기록 (2026-08-06) ═══════════
-- 적용 마이그레이션: page_drawings
-- 이 파일은 재실행 가능한 기록본(신규 환경 복구용). 앱쪽 API 는 src/api/pageDrawings.ts.
--
-- 설계 요약:
--  · 그림을 improvements(개선요청) 행의 jsonb 칸에서 떼어내 **자기 행을 가진 1급 데이터**로 만든 것.
--    종전에는 그림 한 장을 남기려면 게시판 글 + 압정이 반드시 함께 생겼다(사용자: "그림만 그리고 싶을 때도 있다").
--  · 그림 1장 = 행 1개. 압정 대신 **그림 자체가 손잡이** — 호버하면 빛나고 누르면 고치기·지우기가 뜬다.
--  · 화면 매칭은 개선위치(loc) 퍼지 매핑이 아니라 location.pathname 완전 일치.
--    (loc 매핑은 '기타'로 떨어지면 행만 생기고 그림은 저장조차 안 되던 구멍이 있었다)
--  · 좌표(strokes[].p)는 종전과 같은 기준 — 상단바 53 · 레일 64 아래, 폭 1400 중앙정렬 레이어 좌상단 기준 px.
--    스크롤은 따라가지 않는다(레이어가 position:fixed). 이 규약은 이번 분리로 바뀌지 않았다.
--  · 권한: 읽기=로그인 사용자 / 쓰기=구성원 이상 / 수정·삭제=본인 또는 포털 관리자.
--    improvements 와 달리 '담당자' 개념이 없어 관리자에게 고아 그림 회수 경로를 준다.
--  · 이관 없음 — 분리 시점에 improvements.drawing 보유 행이 0건이었다.
--    improvements.drawing 컬럼과 improve_update 의 drawing 분기는 아직 남아 있다(앱은 더 이상 읽지도 쓰지도 않음).
--    실화면 확인 후 별도로 제거할 것 — 되돌릴 수 없는 작업이라 같은 변경에 섞지 않았다.

create table public.page_drawings (
  id bigint generated by default as identity primary key,
  path text not null,
  author text not null default my_name(),
  author_uid uuid not null default auth.uid(),
  strokes jsonb not null,                         -- MemoStroke[] = {c,w,p,k?}
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index page_drawings_path_idx on public.page_drawings (path);

alter table public.page_drawings enable row level security;

-- 'to authenticated' 를 반드시 명시한다 — 빼면 기본 grant 를 타고 anon 에게도 열린다
create policy page_drawings_read on public.page_drawings
  for select to authenticated using (true);

create policy page_drawings_insert on public.page_drawings
  for insert to authenticated with check (is_member() and author_uid = auth.uid());

create policy page_drawings_update on public.page_drawings
  for update to authenticated
  using (is_admin() or author_uid = auth.uid())
  with check (is_admin() or author_uid = auth.uid());

create policy page_drawings_delete on public.page_drawings
  for delete to authenticated
  using (is_admin() or author_uid = auth.uid());
