-- ═══════════ 일반메모(page_notes) — DB 최종 상태 기록 (2026-08-06) ═══════════
-- 적용 마이그레이션: page_notes
-- 앱쪽 API 는 src/api/pageNotes.ts.
--
-- 설계 요약:
--  · 사용자 지시로 '메모'의 정체성을 둘로 나눴다. 종전 메모는 전부 포털개선요청이었는데,
--    구성원 모두가 쓰는 도구가 되면서 개선요청이 아닌 메모가 필요해졌다.
--      - 요청메모 = improvements  … 상태(접수·완료…)·요청번호·게시판 연동 있음. 작성자 + 포털 관리자 열람.
--      - 일반메모 = page_notes    … 상태·번호·**연동 게시판 없음**. 작성자만 열람 + 지목 공유.
--  · 메모 만들 때 둘 중 고르며 기본값은 일반메모다.
--  · 공유는 이름(profiles.name) 배열. 포털 관리자도 공유받지 않으면 못 본다 — 요청메모와 갈리는 지점.
--  · 그림에 붙인 일반메모를 공유하면 **그 그림도 함께 공유된다**(사용자 지시).
--    그래서 page_drawings 읽기 정책을 이 테이블의 shared 를 타도록 고쳤다.
--  · page_drawings 읽기가 종전에는 using(true) 였다 — 로그인만 하면 남의 그림까지 받아 갈 수 있었고
--    화면에서만 걸렀다. 일반메모에 '작성자만'이라는 약속이 생긴 이상 DB에서 막는 게 맞다.
--  · 답글은 없다(요청메모만 improvement_replies 를 쓴다). 개인 메모라 스레드가 필요해지면 그때 붙인다.

create table public.page_notes (
  id bigint generated by default as identity primary key,
  path text not null,
  author text not null default my_name(),
  author_uid uuid not null default auth.uid(),
  content text not null default '',
  shared text[] not null default '{}',
  drawing_id bigint references public.page_drawings(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index page_notes_path_idx on public.page_notes (path);
create index page_notes_drawing_idx on public.page_notes (drawing_id);

alter table public.page_notes enable row level security;

create policy page_notes_read on public.page_notes
  for select to authenticated
  using (author_uid = auth.uid() or my_name() = any(shared));

-- ⚠ drawing_id 소유권 검사(마이그레이션 page_notes_drawing_ownership)가 반드시 있어야 한다.
-- 없으면 구성원이 남의 그림 id 를 적고 shared 에 자기 이름을 넣은 메모를 만들어 그 그림을 열어 볼 수 있다
-- (FK 참조 검사는 RLS 를 우회한다 — 실측 확인). id 가 순차라 전수 수집까지 가능했다.
create policy page_notes_insert on public.page_notes
  for insert to authenticated
  with check (
    is_member() and author_uid = auth.uid()
    and (drawing_id is null or exists (
      select 1 from public.page_drawings d where d.id = drawing_id and d.author_uid = auth.uid()
    ))
  );

-- 고치기·지우기는 작성자만 — 공유받은 사람은 읽기만 한다
create policy page_notes_update on public.page_notes
  for update to authenticated
  using (author_uid = auth.uid())
  with check (
    author_uid = auth.uid()
    and (drawing_id is null or exists (
      select 1 from public.page_drawings d where d.id = drawing_id and d.author_uid = auth.uid()
    ))
  );

create policy page_notes_delete on public.page_notes
  for delete to authenticated
  using (author_uid = auth.uid());

-- ── 그림 열람 (마이그레이션 drawing_req_link_and_note_replies 로 한 번 더 좁혔다) ──
-- 사용자 지시 2026-08-06: 그림도 **작성자 + 공유받은 사람**만. 단 **요청메모가 붙은 그림**은
-- 개선요청의 일부이므로 작성자 + 포털 관리자가 본다(요청메모의 열람 규칙과 같다).
-- 링크(req_num)를 그림 쪽에 둔 이유: 그림의 수정 권한자만 걸 수 있어, 남의 그림을 임의로
-- 개선요청에 엮어 관리자에게 노출시키는 길이 안 생긴다.
--
-- ⚠ exists 절의 `n.author_uid = page_drawings.author_uid` 를 빼지 말 것 —
-- 그림을 여는 메모는 **그 그림 주인이 쓴 메모**여야 한다. 아니면 위 insert 검사와 함께
-- 두 겹으로 막아 둔 '남의 그림 열기'가 다시 열린다.
alter table public.page_drawings add column if not exists req_num bigint;

drop policy if exists page_drawings_read on public.page_drawings;
create policy page_drawings_read on public.page_drawings
  for select to authenticated
  using (
    author_uid = auth.uid()
    or (req_num is not null and is_admin())
    or exists (
      select 1 from public.page_notes n
      where n.drawing_id = page_drawings.id
        and n.author_uid = page_drawings.author_uid
        and my_name() = any(n.shared)
    )
  );

-- ── 일반메모 답글 — 작성자와 공유받은 사람이 주고받는다(사용자 지시 2026-08-06) ──
-- 요청메모의 답글(improvement_replies)은 요청번호에 묶여 있어 그대로 쓸 수 없다.
create table public.page_note_replies (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.page_notes(id) on delete cascade,
  author text not null default my_name(),
  author_uid uuid not null default auth.uid(),
  content text not null,
  created_at timestamptz not null default now()
);
create index page_note_replies_note_idx on public.page_note_replies (note_id);
alter table public.page_note_replies enable row level security;

-- 메모를 볼 수 있는 사람 = 답글을 보고 쓸 수 있는 사람. 고치고 지우는 건 자기 답글만.
create policy page_note_replies_read on public.page_note_replies
  for select to authenticated
  using (exists (select 1 from public.page_notes n
                 where n.id = note_id and (n.author_uid = auth.uid() or my_name() = any(n.shared))));

create policy page_note_replies_insert on public.page_note_replies
  for insert to authenticated
  with check (is_member() and author_uid = auth.uid()
    and exists (select 1 from public.page_notes n
                where n.id = note_id and (n.author_uid = auth.uid() or my_name() = any(n.shared))));

create policy page_note_replies_update on public.page_note_replies
  for update to authenticated
  using (author_uid = auth.uid()) with check (author_uid = auth.uid());

create policy page_note_replies_delete on public.page_note_replies
  for delete to authenticated
  using (author_uid = auth.uid());
